<?php
/**
 * Created by IntelliJ IDEA.
 * User: admin
 * Date: 2/14/2017
 * Time: 6:18 PM
 */
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Class Fitness
 *
 * @property M_fitness model
 */
class Fitness extends Abs_child_manager_1 {
    protected $_parent_field = 'project_id';
    public function __construct() {
        parent::__construct();
        $this->load->model('M_fitness', 'fitness');
        $this->load_more_js("assets/js/front/fitness.js");
    }

    public function setting_class() {
        $this->name = Array(
            "class"  => "fitness",
            "view"   => "fitness",
            "model"  => "m_fitness",
            "object" => "Trọng số hàm thích nghi",
        );
    }

    public function create_save($parent_value, $data = Array(), $data_return = Array(), $skip_validate = FALSE) {
        if (sizeof($data) == 0) {
            $data = $this->input->post();
            $data[$this->_parent_field] = $parent_value;
        }
        if($data['cost']==null ||$data['diff']==null || $data['priority'] ==null|| $data['time'] ==null)
        {
            echo json_encode([
                'state' => 0,
                'msg' => 'Dữ liệu không hợp lệ!
                Cần nhập đầy đủ thông tin các trường.',
            ]);;
            return 0;
        }
        return $this->add_save($data, $data_return, $skip_validate);
    }
    public function manage($parent_value, $data = Array()) {
        $data['fitness'] = $this->model->get($parent_value);
        parent::manage($parent_value, $data);
        $fitness_records = $this->fitness->get_many_by('project_id', $parent_value);
        $data['is_fitness'] = count($fitness_records );
//        var_dump(count($fitness_records));
//        exit();
    }

    public function ajax_list_data($data = Array()) {
        $data['callback']='create_fitness_manage_table_callback';
        return parent::ajax_list_data($data); // TODO: Change the autogenerated stub
    }
}